const data = [ 
{
    custmerId:1,
    name : "nitin",
    id : 221,
    numberofItem : 28,
    contactId : `a2b4c6`, 
    address : `new-delhi_India`,
},
{
    custmerId : 2,
    name : "bix",
    id : 244,
    numberofItem : 28,
    contactId : `p2a2b4c6`, 
    address : `new-delhi_India`,
},
{   custmerId:3,
    name : "rud",
    id : 234,
    numberofItem : 589,
    contactId : `z2b4c6`, 
    address : `new-delhi_India`,
},
{   custmerId:4,
    name : "joc",
    id : 521,
    numberofItem : 374,
    contactId : `a2b4po6`, 
    address : `new-delhi_India`,
}
{   custmerId:3,
    name : "nuc",
    id : 261,
    numberofItem : 48,
    contactId : `a2b13c6`, 
    address : `new-delhi_India`,
},
{   custmerId:6,
    name : "div",
    id : 291,
    numberofItem : 58,
    contactId : `a8b4c6`, 
    address : `new-delhi_India`,
},
{   custmerId:7,
    name : "hud",
    id : 241,
    numberofItem : 12,
    contactId : `a2b4b6`, 
    address : `new-delhi_India`,
},
{   custmerId:8,
    name : "lucas",
    id : 321,
    numberofItem : 128,
    contactId : `c2b4c6`, 
    address : `new-delhi_India`,
},
{   custmerId:9,
    name : "max",
    id : 211,
    numberofItem : 23,
    contactId : `a2b6c6`, 
    address : `new-delhi_India`,
},
{   custmerId:10,
    name : "abhi",
    id : 227,
    numberofItem : 38,
    contactId : `a2x4c6`, 
    address : `new-delhi_India`,
}
]

console.log(data);

